### State of this project: Getting much better. DNS and DHCP both seem stable

IMPORTANT: If the DHCP server doesn't respond to clients, ensure the server's firewall is not blocking port 67/udp. Other things that commonly affect the DHCP server include AppArmor, SELinux, network firewalls, and NAT routers. See the Troubleshooting section below for more information.

CAUTION: Deploying DHCP services on a subnet that already has them can cause mind-numbingly-difficult-to-troubleshoot problems and make the offender surprisingly unpopular for generations to come. See the Troubleshooting section below to verify that no other DHCP services are running on your subnet.

#### This container requires podman and optionally nmap and/or telnet to be installed on the target server

#### Create and deploy the DNS or DNS+DHCP container
* Clone this repo to the target server: `git clone https://github.com/alexarnoldy/opensuse-dnsmasq-container.git && cd opensuse-dnsmasq-container`

* Update the dnsmasq.conf and dnsmasq_hosts files to suit your environment

* Build the container: `sudo podman build -t localhost/opensuse_dnsmasq_container:latest .`

* Set this variable to the IP address dnsmasq should listen on: `export DNS_IP=`

* Set this variable this repo diretory (alternately, to a directory containing the appropriate dnsmasq.conf, dnsmasq_hosts, and resolv.dnsmasq files): `export CONF_DIR=${PWD}`

* Make sure the IP address is correctly configured on this host:  `ip a | grep -B2 ${DNS_IP}`

* Run a DNS only container:  
----
sudo podman run -d --name opensuse-dnsmasq-container \
--mount type=bind,source=$CONF_DIR,target=/var/dnsmasq \
-p $DNS_IP:53:53/tcp -p $DNS_IP:53:53/udp \
--cap-add=NET_ADMIN --net host localhost/opensuse_dnsmasq_container:latest
----

* Run a DNS+DHCP container:  
----
sudo podman run -d --name opensuse-dnsmasq-container \
--mount type=bind,source=$CONF_DIR,target=/var/dnsmasq \
-p $DNS_IP:53:53/tcp -p $DNS_IP:53:53/udp -p $DNS_IP:67:67/udp \
--cap-add=NET_ADMIN --net host localhost/opensuse_dnsmasq_container:latest
----

* Copy the opensuse-dnsmasq.service systemd file into place: `sudo cp -p opensuse-dnsmasq.service /etc/systemd/system/`
* Reload systemd: `sudo systemctl daemon-reload`
* Start and enable the systemd opensuse-dnsmasq.service: `sudo systemctl --now enable opensuse-dnsmasq.service`
* Check the status of the opensuse-dnsmasq.service: `systemctl status opensuse-dnsmasq.service`
* Check that the ports are being monitored: `ss -npr --listening`


#### Updates to the local DNS records or the dnsmasq configuration require restarting the container:  
* Update dnsmasq_hosts and/or dnsmasq.conf files 
* Restart the container: `sudo podman restart opensuse-dnsmasq-container`

#### Troubleshooting
* Ensure the container is running: `sudo podman ps -a`
** The "STATUS" field should show the amount of time the container has been running
** If the STATUS is EXITED, run the command `sudo podman logs opensuse-dnsmasq-container` to see the error that stopped the container
* Check to see if the host is monitoring the DNS (53/tcp and 53/udp) and/or DHCP (67/udp) port on the correct IP address: 
** `ss -npr --listening`
* Ensure a server firewall isn't blocking the ports (Google for how to work with your firewall)
* From another host in the same subnet, use telnet or nmap to see if the ports are available
** I.e. `telnet <server> IP 53` for DNS
*** Note: For TCP ports only
** I.e. `sudo nmap -sT -sU -p 53 <server IP> for DNS TCP and UDP ports
** I.e. `sudo nmap -sU -p 67 --script=dhcp-discover <server IP>` for DHCP
*** Note that a result of "67/udp open|filtered dhcps" means the port is monitored but the DHCP server is not responding to requests
*** Example of a valid DHCP server response:
----
67/udp open  dhcps
| dhcp-discover: 
|   DHCP Message Type: DHCPACK
|   Server Identifier: 192.168.1.10
|   Broadcast Address: 192.168.1.255
|   Domain Name: example.com
|   Domain Name Server: 192.168.1.10
|   Router: 192.168.1.1
|_  Subnet Mask: 255.255.255.0
MAC Address: 52:54:00:93:EB:A1
----
* To detect DHCP servers on a subnet `sudo nmap -sU -p 67 --script=dhcp-discover <network>/<CIDR mask> | less` 
** I.e. `sudo nmap -sU -p 67 --script=dhcp-discover 192.168.1.0/24 | less`
*** May take 10 minutes or more to complete. Press Enter to get a guesstimate of when nmap will finish

NOTE: To make DNS-only service HA, run multiple instances in the same subnet with identical configurations. Run an instance of https://github.com/alexarnoldy/opensuse-keepalived-container with each to manage a virtual IP address. Updates must be made to all instances and all instances must be restarted. Failure to do so will lead to inconsistent results.

NOTE: To make DNS+DHCP service HA, run multiple instances in the same subnet with identical configurations, except for dhcp-range, which must be unique for each instance. Run an instance of https://github.com/alexarnoldy/opensuse-keepalived-container with each to manage a virtual IP address. Updates must be made to all instances and all instances must be restarted. Failure to do so will lead to inconsistent results


// vim: set syntax=asciidoc:

