### State of this project: Getting much better. DNS and DHCP both seem stable

IMPORTANT: If DHCP server doesn't respond to clients, ensure server, client, nor intermediate networks are blocking DHCP ports.

* Clone this repo to the target server

* Update the dnsmasq.conf, dnsmasq_hosts, and resolv.dnsmasq files to suit your environment

* Build the container: `sudo docker build -t opensuse_dnsmasq_container:latest .`

* Set this variable to the IP address dnsmasq should listen on: `export DNS_IP=`

* Set this variable to the directory containing this repo: `export CONF_DIR=`

* Make sure the IP address is correctly configured on this host:  `ip a | grep -B2 "$DNS_IP"`

* Run a DNS only container:  
----
docker run -d --restart=always --name opensuse-dnsmasq-container --mount type=bind,source=$CONF_DIR,target=/var/dnsmasq \
-p $DNS_IP:53:53/tcp -p $DNS_IP:53:53/udp --cap-add=NET_ADMIN opensuse_dnsmasq_container:latest
----

* Run a DNS+DHCP container:  
----
docker run -d --restart=always --name opensuse-dnsmasq-container --mount type=bind,source=$CONF_DIR,target=/var/dnsmasq \
-p $DNS_IP:53:53/tcp -p $DNS_IP:53:53/udp -p $DNS_IP:67:67/udp --cap-add=NET_ADMIN opensuse_dnsmasq_container:latest
----

.To update local DNS records or the dnsmasq configuration:  
* Update caasp_hosts and/or dnsmasq.conf files (updating the resolv.dnsmasq requires rebuilding the container image)
* Restart the container: `docker restart caasp_dns`



// vim: set syntax=asciidoc:

